# ========== log4jdbc ???? ==========

# ????SLF4J??????
# log4jdbc???????SLF4J????Log4j2??
log4jdbc.spylogdelegator.name=net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator

# ??????????
# ???false??????????????????
log4jdbc.auto.load.popular.drivers=false

# ?????MySQL JDBC???
# log4jdbc?????????????SQL
log4jdbc.drivers=com.mysql.cj.jdbc.Driver

# SQL?????????0??????
# ??SQL?????????
log4jdbc.dump.sql.maxlinelength=0

# ????SQL???????
log4jdbc.dump.sql.select=true
log4jdbc.dump.sql.insert=true
log4jdbc.dump.sql.update=true
log4jdbc.dump.sql.delete=true

# ??SQL????????
log4jdbc.trim.sql=true
# ??SQL????????
log4jdbc.trim.sql.extrablanklines=true
